"""Frontend improvements

Revision ID: 009c54e579c0
Revises: d0415953db44
Create Date: 2026-06-25 17:52:37.034998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c54e579c0'
down_revision = 'd0415953db44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_versions', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
