"""add media_versions and public_id

Revision ID: d0415953db44
Revises: b7bd43b851d1
Create Date: 2026-06-25 16:20:51.014836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0415953db44'
down_revision = 'b7bd43b851d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_media_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_public_id'))
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
